# -*- coding: utf-8 -*-
"""Dice Rolling Simulation - D&D Version

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jiL4JnE5LjR05JjmKVBdvKGPttylwuCG
"""

import random

def roll_dice(num_dice, sides):
    rolls = []
    for _ in range(num_dice):
        rolls.append(random.randint(1, sides))
    return rolls, sum(rolls)


def main():
    print("Welcome to the Dice Rolling Simulator - D&D Edition!")

    while True:  # MAIN LOOP

        while True:
              user_input = input("\nEnter roll (e.g. 3d6): ").lower().strip()

                # Must contain 'd'
              if 'd' not in user_input:
                  print("Invalid format. Please use format like 3d6.")
                  continue

              parts = user_input.split("d")

                # Must be split into exactly 2 parts
              if len(parts) != 2:
                  print("Invalid format. Please use format like 3d6.")
                  continue

              try:
                  num_dice = int(parts[0])
                  sides = int(parts[1])

              except ValueError:
                  print("Invalid numbers entered. Please use format like 3d6.")
                  continue

              # Validation
              if not (1 <= num_dice <= 10):
                  print("Number of dice must be 1–10.")
                  continue

              if sides < 2:
                  print("Dice must have at least 2 sides.")
                  continue

              break # valid input → exit loop

        # Roll dice
        rolls, total = roll_dice(num_dice, sides)

        print("\nResults:")
        print("Rolls:", rolls)
        print("Total:", total)

        # Ask again
        again = input("\nRoll again? Type 'y' to continue or 'n' to exit ").lower().strip()

        if again == "n":
            print("Goodbye!")
            break


if __name__ == "__main__":
    main()